#!/usr/bin/env bash
set -e

version() {
  echo "Bats 0.1.0"
}

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

expand_path() {
  { cd "$(dirname "$1")" 2>/dev/null
    local dirname="$PWD"
    cd "$OLDPWD"
    echo "$dirname/$(basename "$1")"
  } || echo "$1"
}

BATS_LIBEXEC="$(abs_dirname "$0")"
export BATS_PREFIX="$(abs_dirname "$BATS_LIBEXEC")"
export PATH="$BATS_LIBEXEC:$PATH"

if [ "$1" = "-v" ] || [ "$1" = "--version" ]; then
  version
  exit 0
fi

filename="$1"
if [ -z "$filename" ]; then
  { version
    echo "usage: $0 <filename>"
  } >&2
  exit 1
else
  shift
fi

exec bats-exec "$(expand_path "$filename")" "$@"
